// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.example.protocol.tree



object TreeProto {
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """Cgp0cmVlLnByb3RvEhRjb20uZXhhbXBsZS5wcm90b2NvbCIcCgRMZWFmEhQKBXZhbHVlGAEgASgFUgV2YWx1ZSJ2CgZCcmFuY
  2gSNAoEbGVmdBgBIAEoCzIgLmNvbS5leGFtcGxlLnByb3RvY29sLkJpbmFyeVRyZWVSBGxlZnQSNgoFcmlnaHQYAiABKAsyIC5jb
  20uZXhhbXBsZS5wcm90b2NvbC5CaW5hcnlUcmVlUgVyaWdodCJ/CgpCaW5hcnlUcmVlEjAKBGxlYWYYASABKAsyGi5jb20uZXhhb
  XBsZS5wcm90b2NvbC5MZWFmSABSBGxlYWYSNgoGYnJhbmNoGAIgASgLMhwuY29tLmV4YW1wbGUucHJvdG9jb2wuQnJhbmNoSABSB
  mJyYW5jaEIHCgV2YWx1ZWIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, Seq(
    ))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}